AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    1f1a32b3-072e-46ef-8815-6451bea883f2:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 190ipp
      z: 0
      embeds: []
    41c92a16-5756-4f05-8acd-93e3e7d9b78d:
      size:
        width: 60
        height: 60
      position:
        x: -80.16666666666667
        'y': 15.942667643229166
      z: 0
Resources:
  DDBT1TDK8:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: asgName
          AttributeType: S
        - AttributeName: region
          AttributeType: S
      TableName: asgState
      KeySchema:
        - AttributeName: asgName
          KeyType: HASH
        - AttributeName: region
          KeyType: RANGE
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1f1a32b3-072e-46ef-8815-6451bea883f2
  DDBT4E67X:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: ecsArn
          AttributeType: S
        - AttributeName: region
          AttributeType: S
      TableName: ecsStatev2
      KeySchema:
        - AttributeName: ecsArn
          KeyType: HASH
        - AttributeName: region
          KeyType: RANGE
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 41c92a16-5756-4f05-8acd-93e3e7d9b78d
