AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    8ce2d05e-aa87-4ef0-8f33-bfd22ecbc207:
      size:
        width: 60
        height: 60
      position:
        x: 170
        'y': 220
      z: 0
      embeds: []
      dependson:
        - a0e598b9-856a-4dcb-b715-f9fe0ed0ab9f
    a0e598b9-856a-4dcb-b715-f9fe0ed0ab9f:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 140
      z: 0
      embeds: []
    478df7a2-24c7-4f33-9cd0-701ecaeb9b82:
      size:
        width: 60
        height: 60
      position:
        x: 89.66920339917384
        'y': 231.4614713366727
      z: 0
      embeds: []
      isassociatedwith:
        - a0e598b9-856a-4dcb-b715-f9fe0ed0ab9f
    783436e9-93dd-4f15-b38d-ecb517306b31:
      source:
        id: 478df7a2-24c7-4f33-9cd0-701ecaeb9b82
      target:
        id: a0e598b9-856a-4dcb-b715-f9fe0ed0ab9f
      z: 11
Parameters:
  LambdaName:
    Default: SleepSaverProd
    Type: String
  LambdaDescription:
    Default: 'Lambda that will look for the Tag DEVDAY : TRUE and will put common assets to sleep at the end of the day, and will start them on next day'
    Type: String
  DayScheduleExpression:
    Default: 'cron(0 4 ? * 2-6 *)'
    Type: String
  NightScheduleExpression:
    Default: 'cron(45 18 * * ? *)'
    Type: String

Resources:
  #Edit 3 S3Key for the zip containing lambda code
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Role:  !GetAtt IAMRSLEEPLAMSRVC.Arn
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Description: !Ref LambdaDescription
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          ECSDBREGION: eu-west-2
          ECSDYNTABLE: ecsStatev2
          REGIONLIST: 'eu-west-1, eu-west-2'
          SEARCHTAG: DEVDAY
          ASGDYNTABLE: asgState
          ASGREGION: eu-west-2
      Code:
        S3Bucket: 'evg-sleepsaver-cf'
        S3Key: 'sleepsaverlambda.zip'
    DependsOn:
      - IAMPDYN
  IAMPDYN:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: SLEEPECSDYNRW
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:Scan'
            Resource:
              - !Sub
                - 'arn:aws:dynamodb:${REG}:${ACC}:table/asgState'
                - ACC: !Ref "AWS::AccountId"
                  REG: !Ref "AWS::Region"
              - !Sub
                - 'arn:aws:dynamodb:${REG}:${ACC}:table/ecsStatev2'
                - ACC: !Ref "AWS::AccountId"
                  REG: !Ref "AWS::Region"
      Roles:
        - !Ref IAMRSLEEPLAMSRVC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8ce2d05e-aa87-4ef0-8f33-bfd22ecbc207
    DependsOn:
      - IAMRSLEEPLAMSRVC
  NightRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: SleepSaverNighRule
      Description: sleepsaverProd Start of Night Schedule
      ScheduleExpression: !Ref NightScheduleExpression
      Targets:
        - Id: !Ref LambdaName
          Arn: !GetAtt LambdaFunction.Arn
          Input: '{ "event": "STOP"}'
      State: ENABLED
  DayRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: SleepSaverDayRule
      Description: sleepsaverProd Start of Day Schedule
      ScheduleExpression: !Ref DayScheduleExpression
      Targets:
        - Id: !Ref LambdaName
          Arn: !GetAtt LambdaFunction.Arn
          Input: '{ "event": "START"}'
      State: ENABLED
  InvokeLambdaRule:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LambdaName
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
    DependsOn: LambdaFunction


  IAMRSLEEPLAMSRVC:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: sleepSaver-Lambda-execution-role
      Description: 'Sleepsaver exeuction role'
      MaxSessionDuration: 4600
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonECS_FullAccess'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a0e598b9-856a-4dcb-b715-f9fe0ed0ab9f
  IAMPLamEX:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: AWSLambdaBasicExecutionRole-Sleepsaver
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'logs:CreateLogGroup'
            Resource:
              - !Sub
                - 'arn:aws:logs:${REG}:${ACC}:*'
                - ACC: !Ref "AWS::AccountId"
                  REG: !Ref "AWS::Region"
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource:
              - !Sub
                - 'arn:aws:logs:${REG}:${ACC}:log-group:/aws/lambda/sleepsaver:*'
                - ACC: !Ref "AWS::AccountId"
                  REG: !Ref "AWS::Region"
      Roles:
        - !Ref IAMRSLEEPLAMSRVC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 478df7a2-24c7-4f33-9cd0-701ecaeb9b82
